# Runs on pull requests against master, and on master branch

name: Haskell Lint

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/hlint.yml'
      - 'app/**/*.hs'
      - 'src/**/*.hs'
      - 'test/**/*.hs'
jobs:
  hlint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            hlint: 3.1.6  # default for actions-hlint-setup
          - os: ubuntu-latest
            hlint: '3.10'

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HLINT_ACTION_LOG_LEVEL: debug
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1
        with:
          version: ${{ matrix.hlint }}

      - name: Haskell Lint
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["src/", "test/", "app/"]'
          fail-on: warning
