name: Release Online
on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"

  # also on manual trigger
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version number for the release'
        required: true

jobs:
  build-js:
    name: Create JS for Web-Version
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      volumes:
        - /:/host

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: unknown-js
            ghcup: https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup
            ghc: javascript-unknown-ghcjs-9.10.2
            emsdk: 3.1.74

    steps:

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y autoconf gcc g++ libffi-dev curl liblzma-dev git xz-utils make python3

      - name: Install ghcup and cabal
        run: |
          curl --proto '=https' --tlsv1.2 -sSf ${{ matrix.ghcup }}  > /usr/bin/ghcup
          chmod +x /usr/bin/ghcup
          echo "$HOME/.ghcup/bin" $GITHUB_PATH
          ghcup config add-release-channel cross
          ghcup install cabal --force -i /usr/local/bin
        shell: bash

      - name: Install emscripten and GHC
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ matrix.emsdk }}
          ./emsdk activate ${{ matrix.emsdk }}
          source ./emsdk_env.sh
          emconfigure ghcup install ghc --force -i /usr/local --set ${{ matrix.ghc }}
          ln -sf /usr/local/bin/javascript-unknown-ghcjs-hsc2hs /usr/local/bin/hsc2hs-ghc-9.10.2
        shell: bash

      - uses: actions/checkout@v4

      - name: create ~/.local/bin
        run: mkdir -p "$HOME/.local/bin"
        shell: bash

      - run: echo "HOME=$HOME" >> $GITHUB_ENV
        shell: bash

      - name: Freeze
        run: |
          cabal update
          cabal freeze -w /usr/local/bin/javascript-unknown-ghcjs-ghc --with-hc-pkg /usr/local/bin/javascript-unknown-ghcjs-ghc-pkg

      - name: Cache store
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cabal/store
          key: ${{ matrix.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: |
          source /emsdk/emsdk_env.sh
          emconfigure cabal build -w /usr/local/bin/javascript-unknown-ghcjs-ghc --with-hc-pkg /usr/local/bin/javascript-unknown-ghcjs-ghc-pkg
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hadolint-${{ matrix.target }}
          path: ~/.local/bin/hadolint
          retention-days: 3
